package com.lily.lilyium.mapper

import com.lily.lilyium.api.model.Album as ApiAlbum
import com.lily.lilyium.localDB.model.Album as DbAlbum

fun ApiAlbum.toDbAlbum(): DbAlbum = DbAlbum(
    id = id,
    parent = parent,
    isDir = isDir,
    title = title,
    album = album,
    artist = artist,
    track = track,
    year = year,
    genre = genre,
    coverArt = coverArt,
    size = size,
    contentType = contentType,
    suffix = suffix,
    transcodedContentType = transcodedContentType,
    transcodedSuffix = transcodedSuffix,
    duration = duration,
    bitRate = bitRate,
    bitDepth = bitDepth,
    samplingRate = samplingRate,
    channelCount = channelCount,
    path = path,
    isVideo = isVideo,
    userRating = userRating,
    averageRating = averageRating,
    playCount = playCount,
    discNumber = discNumber,
    created = created,
    starred = starred,
    albumId = albumId,
    artistId = artistId,
    type = type,
    mediaType = mediaType,
    bookmarkPosition = bookmarkPosition,
    originalWidth = originalWidth,
    originalHeight = originalHeight,
    played = played,
    bpm = bpm,
    comment = comment,
    sortName = sortName,
    musicBrainzId = musicBrainzId,
    genresJson = genresJson,
    artistsJson = artistsJson,
    albumArtistsJson = albumArtistsJson,
    contributorsJson = contributorsJson,
    moodsJson = moodsJson,
    replayGainJson = replayGainJson,
    displayArtist = displayArtist,
    displayAlbumArtist = displayAlbumArtist,
    displayComposer = displayComposer,
    explicitStatus = explicitStatus
)
